export const COUNTRY_REQUEST = "COUNTRY_REQUEST";
export const COUNTRY_RECEIVE = "COUNTRY_RECEIVE";
export const COUNTRY_FAIL = "COUNTRY_FAIL";
export const SEPARATE_COUNTRY = "SEPARATE_COUNTRY";
export const COUNTRY_NEIGHBORS_REQUEST = "COUNTRY_NEIGHBORS_REQUEST";
export const COUNTRY_NEIGHBORS_RECEIVE = "COUNTRY_NEIGHBORS_RECEIVE";
export const COUNTRY_NEIGHBORS_FAIL = "COUNTRY_NEIGHBORS_FAIL";
export const COUNTRY_COMMON_NEIGHBORS = "COUNTRY_COMMON_NEIGHBORS";
